# Exported from Render on 2024-04-19T15:23:56Z
services:
- type: web
  name: Calculator.VTU
  runtime: node
  repo: https://github.com/Coderdhanush-2003/Calculator.VTU
  plan: free
  region: oregon
  buildCommand: yarn
  startCommand: yarn start
version: "1"
